### ISSUE TITLE
missing/unneccessary css sourcemaps for ckeditor plugins

### ISSUE THREAD

**Issue by Lindsay-Needs-Sleep** [ckeditor/vite-plugin-ckeditor5#14]
I get this error in chrome dev tools when I run `vite --host --port 8346`

`DevTools failed to load source map: Could not load content for http://localhost:8346/ckeditor_src/node_modules/@ckeditor/<anything>.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`
![image](https://github.com/ckeditor/vite-plugin-ckeditor5/assets/51773923/6b68fb48-0cca-4afa-8adf-2573398423e0)

**vite.config.js**
```js
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);

import { defineConfig } from 'vite';
import ckeditor5 from '@ckeditor/vite-plugin-ckeditor5';

export default defineConfig(({ command, mode, ssrBuild }) => {
    const prod = mode == 'production';
    return {
        // build: {...}
        plugins: [
            ckeditor5({ theme: require.resolve('@ckeditor/ckeditor5-theme-lark') }),
        ],
        server: {
            watch: {
                usePolling: true,
            },
        }
    };
});
```

Filesystem (it is at the root, using docker):
```
/ckeditor_src
/ckeditor_src/node_modules
/ckeditor_src/index.html
/ckeditor_src/package.json
/ckeditor_src/vite.config.js
```

My project is essentially the starter project produced by the ck source builder, I just switched from webpack to vite.

I believe the `/*# sourceMappingURL=/ckeditor_src/node_modules/@ckeditor/ckeditor5-<...>.css.map */` is added by `vite-ckeditor5-styles-loader` (tried to debug and figure out what was going on....)

This does not affect/occur in production builds.

**Comment by Lindsay-Needs-Sleep** [comment]
As an ugly workaround I have modified my `vite.config.js` to disable (remove) the `sourceMappingURL`.

```js
        plugins: [
            ckeditor5({ theme: require.resolve('@ckeditor/ckeditor5-theme-lark') }),
            {
                transform: (code, id) => {
                    if (!id.match('@ckeditor') || !id.match('.css')) return { code };
                    prod && console.error('WARNING: Removing SourceMappingURL for ' + id);
                    return {
                        code: code.replace('/*# sourceMappingURL=','/*'),
                    };
                }
            },
        ],
```

**Comment by Witoso** [comment]
Please update to today's release: https://github.com/ckeditor/vite-plugin-ckeditor5/releases/tag/v0.1.3

Sorry for the issue!

**Comment by Lindsay-Needs-Sleep** [comment]
Oh cool! I'll try it out later tomorrow! Thanks! :D

**Comment by Lindsay-Needs-Sleep** [comment]
@Witoso Yep! All better!  tyvm! :D
