### ISSUE TITLE
Support Source Maps

### ISSUE THREAD

**Issue by HaNdTriX** [ckeditor/vite-plugin-ckeditor5#8]
Using this plugin with vite, logs the following warning when running `vite build`

```log
Sourcemap is likely to be incorrect: a plugin (vite-ckeditor5-styles-loader) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
```

## More info

- https://vitejs.dev/guide/api-plugin.html#transforming-custom-file-types
- https://github.com/ckeditor/vite-plugin-ckeditor5/blob/master/src/loaders/stylesLoader.ts#L61-L63

**Comment by Witoso** [comment]
TBH I have not observed that in `vite build`. What build configuration do you have?

**Comment by HaNdTriX** [comment]
The warning pops up as soon as sourcemaps are enabled. Here is my `vite.config.ts`

```ts
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import ckeditor5 from "@ckeditor/vite-plugin-ckeditor5";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);

// https://vitejs.dev/config/
export default defineConfig({
  build: {
    // The issue happens when the sourcemap is enabled (true | 'hidden' | 'inline').
    sourcemap: true, // <- 🐞
  },

    // TODO: Remove this fix once the following issue is resolved:
  // https://github.com/ckeditor/ckeditor5/issues/13922
  optimizeDeps: {
    esbuildOptions: {
      legalComments: "none",
    },
  },
  plugins: [
    vue(),
    ckeditor5({ theme: require.resolve("@ckeditor/ckeditor5-theme-lark") }),
  ],
});
```

**Comment by Witoso** [comment]
@LukaszGudel is this something you could tweak?

**Comment by HaNdTriX** [comment]
## Short reproduction instructions

To reproduce this issue just add the following to your `vite.config.ts` and run `vite build`:

```diff
  ...
+  build: {
+    sourcemap: true
+  },
  ...
```

**Comment by LukaszGudel** [comment]
The issue with warnings was fixed in #9 and will be available in the next release of the plugin.

**Comment by HaNdTriX** [comment]
@LukaszGudel Thanks a lot for fixing this issue 🙏. Is there already a release date? It would be awesome if we could use these changes.

**Comment by HaNdTriX** [comment]
Thanks a lot! 🙏
